#!/bin/bash

eval "$(pyenv init -)"
pyenv shell 3.7.7

mkdir -p macos

./build_deps_37 ${PWD}/macos ${PWD}/distfiles

cp -R ${PWD}/mac_bundle/ ${PWD}/macos/mac_bundle/

tar -czf MacDistFiles_37.tar.gz ./macos
