#!/bin/bash

eval "$(pyenv init -)"
pyenv shell 3.9.2

mkdir -p macos

./build_deps_39 ${PWD}/macos ${PWD}/distfiles

cp -R ${PWD}/mac_bundle/ ${PWD}/macos/mac_bundle/

tar -czf MacDistFiles_39.tar.gz ./macos
